services:
  # Caddy reverse proxy with SSL
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./logs:/var/log/caddy
    networks:
      - club-network
    restart: unless-stopped
    depends_on:
      - homer
      - go-test-server
    # Security options
    security_opt:
      - no-new-privileges:true

  # Homer dashboard (homepage)
  homer:
    image: b4bz/homer:latest
    volumes:
      - ./assets:/www/assets:ro
    environment:
      - INIT_ASSETS=0
    networks:
      - club-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  # NOTE: File services provided by separate NAS deployment
  # Configure your NAS services and update Caddy routing accordingly

  # Go test server
  go-test-server:
    build:
      context: .
      target: production
    volumes:
      - ./templates:/root/templates:ro
    networks:
      - club-network
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  club-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: